### ISSUE TITLE
Invariant Violation: onlyChild must be passed a children with exactly one child. 

### ISSUE THREAD

**Issue by andyyou** [gajus/react-css-modules#12]
At first I am not quite sure it's an issue or not. I attempt to use react-css-modules in my demo project that integerate Rails + webpack etc. 

I make dynamic components in an array, the problem is [gist](https://gist.github.com/andyyou/8729a52344fa33efaec0#file-react-css-modules-js-L75-L79) 
when array has less than two items will meet
`Invariant Violation: onlyChild must be passed a children with exactly one child.` exception.
, and only happened with `react-css-modules`. If I remove `react-css-modules` everything work fine

<script src="https://gist.github.com/andyyou/8729a52344fa33efaec0.js"></script>

I have no idea that I did something wrong or it's an issue

The full project is [here](https://github.com/andyyou/rails-webpack-demo)

**Comment by andyyou** [comment]
#13

**Comment by gajus** [comment]
This has been fixed in version https://github.com/gajus/react-css-modules/tree/3.0.3.

**Comment by matiaslarsson** [comment]
Hmm, I'm still getting the same error on 3.0.3. If I remove CSSModules everything renders OK.

```
import CSSModules from 'react-css-modules';
import styles from './schedule.css';

...

@CSSModules(styles)
export default class extends React.Component {
	constructor(props) {
		super(props);
	}

	render() {

		var scheduleDays = [], title = null;
		var firstDay = this.props.days[0];
		if(firstDay) {
			scheduleDays = renderDays(this.props.days);
		}

	    return <div>{scheduleDays}</div>
  	}
}

...

```

Returns the error

```
Uncaught (in promise) Error: Invariant Violation: onlyChild must be passed a children with exactly one child.
    at invariant (webpack:///./~/react/lib/invariant.js?:42:15)
    at Object.onlyChild [as only] (webpack:///./~/react/lib/onlyChild.js?:29:44)
    at linkClass (webpack:///./~/react-css-modules/dist/linkClass.js?:80:65)
    at _class.render (webpack:///./~/react-css-modules/dist/index.js?:45:51)
    at _class.module.exports.proto.(anonymous function) (webpack:///./~/react-hot-loader/~/react-hot-api/modules/makeAssimilatePrototype.js?:15:37)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (webpack:///./~/react/lib/ReactCompositeComponent.js?:789:34)
    at ReactCompositeComponentMixin._renderValidatedComponent (webpack:///./~/react/lib/ReactCompositeComponent.js?:816:14)
    at ReactPerf.measure.wrapper (webpack:///./~/react/lib/ReactPerf.js?:70:21)
    at ReactCompositeComponentMixin._updateRenderedComponent (webpack:///./~/react/lib/ReactCompositeComponent.js?:746:36)
    at ReactCompositeComponentMixin._performComponentUpdate (webpack:///./~/react/lib/ReactCompositeComponent.js?:726:10)
```

I am using https://github.com/HenrikJoreteg/hjs-webpack and modifying the webpack config like this to support react-css-modules (and some ES7).
```
config.module.loaders.forEach(function (filter) {

	// Babel Stage 0 for ES7 decorators
	if (filter.loaders) {
		filter.loaders.forEach(function(loader, idx, arr) {
			if (loader === 'babel-loader') {
				arr[idx] = 'babel-loader?stage=0'
			}
		})
	}

	// React-css-modules
	if(filter.loader === 'style-loader!css-loader!postcss-loader') {
		filter = {
			test: /\.css$/,
			loader: ExtractTextPlugin.extract('style', 'css?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]')
		}
	}
})

config.plugins.push(new ExtractTextPlugin('app.css', { allChunks: true }));
```

I've tried ES6 and ES5 style code but they all give me the same error.

**Comment by gajus** [comment]
@matiaslarsson Please provide an example React Component class that causes the error (without dependencies), e.g.

```js
export default class extends React.Component {
    render () {
            // Logic to construct `scheduleDays` variable that causes the error.
            return <div>{scheduleDays}</div>
    }
}
```

**Comment by matiaslarsson** [comment]
I have tried creating a reduced test case, but can't get it to fail. I think it has something to do with Alt and actions updating the store asynchronously but even my simple test case with Alt worked. Will get back to you when I have the time to reduce the app to something that fails.

```

render() {
		var scheduleDays = [];
		var firstDay = this.props.days[0];
		
		if(firstDay && firstDay.date) {
			scheduleDays = this.props.days.map(day => {
				return <div>Hello: {day.date}</div>
			});
		}
	    return <div>{scheduleDays}</div>
  	}
}

```

**Comment by matiaslarsson** [comment]
Or it helps if one uses data that is similar to the live environment. ;)

The problem occurs when iterating over an array with one item.
[{date: "2015-09-03"}] will fail.
[{date: "2015-09-03"}, {date: "2015-09-04"}] will work.

```
@CSSModules(styles)
class Schedule extends React.Component {
	render() {
		var	scheduleDays = [{date: "2015-09-03"}].map(day => {
			return <div>Hello: {day.date}</div>
		});
		
	    return <div>{scheduleDays}</div>
  	}
}
```

**Comment by gajus** [comment]
I have managed to replicate the issue:

```js
import React from 'react';
import styles from './car.css';
import CSSModules from 'react-css-modules';
import _ from 'lodash';

class Car extends React.Component {
    constructor () {
        super();

        this.state = {
            dates: []
        };
    }

    componentDidMount () {
        this.setState({
            dates: [
                <li>{Math.random()}</li>
            ]
        });
    }

    render () {
        return <ul>{this.state.dates}</ul>
    }
}

export default CSSModules(Car, styles);
```

Now looking into how to solve it.

**Comment by matiaslarsson** [comment]
Thanks!

**Comment by gajus** [comment]
@matiaslarsson Please update to version 3.0.4 and test it.

**Comment by matiaslarsson** [comment]
@gajus 3.0.4 works like a charm! Thanks for the quick fix!

**Comment by gajus** [comment]
Woohoo!
