### ISSUE TITLE
Unknown prop `styleName` on <div> tag.

### ISSUE THREAD

**Issue by gajus** [gajus/react-css-modules#147]
Tracking:
- https://gist.github.com/jimfb/d99e0678e9da715ccf6454961ef04d1b

**Comment by gajus** [comment]
Need to investigate whats the proper action.

**Comment by jrajav** [comment]
It seems like the official word from Reactjs team (via Reactiflux channel and https://twitter.com/dan_abramov/status/749716439330881536) is to use a data- attribute instead. If that seems a little too awkward, at least the ability to configure the attribute away from just `styleName` would be good, as these errors now pollute our whole test suite:

```
Warning: Unknown prop `styleName` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in Unknown
    in Element
```

See https://github.com/jrajav/ava-test for a running example.

**Comment by gajus** [comment]
Fixed thanks to https://github.com/gajus/react-css-modules/pull/148. v3.7.7 released.

**Comment by goodbomb** [comment]
I'm still seeing this while using v3.7.7.

More specifically, I see it happening on modules that are also wrapped using Redux-Form.

**Comment by gajus** [comment]
> More specifically, I see it happening on modules that are also wrapped using Redux-Form.

Please create a simple repository to reproduce the issue.

**Comment by goodbomb** [comment]
I'll follow-up when I've got something for you to look at. Cheers!

**Comment by goodbomb** [comment]
Actually, I'm not sure creating a whole repo for this would be necessary. Here's an example component that I'm currently working with that is producing the error (I've reproduced this issue in more than one component now).

I'm using:
```
    "react-css-modules": "^3.7.7",
    "react-redux": "^4.4.5",
    "redux": "^3.5.2",
    "redux-form": "^6.0.0-rc.3"
```

```
import React, { Component, PropTypes } from 'react';
import { reduxForm, Field } from 'redux-form';
import { Checkbox, FlatButton } from 'material-ui';
import { ContentAddCircle } from 'material-ui/svg-icons';
import { updateOrgMember } from './orgs';
import { ROLES } from 'constants';

import cssModules from 'react-css-modules';
import styles from 'app/orgs/orgs.css';

class OrgMembersEdit extends Component {

    constructor(props) {
        super(props);
    }

    handleFormSubmit = (props) => {
        console.log('it works!');
    };

    renderMemberRoleField = (field) => {
        return (
            <input
                    type="checkbox"
                    checked={field.input.value ? true : false}
                    onCheck={field.input.onChange}
                    {...field.input}
                />
        );
    };

    render() {
        const {
            handleSubmit
        } = this.props;

        // <div styleName="edit-member-form"> below causes the error.
        return (
            <div styleName="edit-member-form">
                <form onSubmit={handleSubmit(this.handleFormSubmit)}>
                    <div className="form-field role">
                        <Field
                            name="isLead"
                            component={this.renderMemberRoleField}
                        />
                    </div>
                    <div className="form-footer">
                        <button>Submit</button>
                    </div>
                </form>
            </div>
        );
    }
}

OrgMembersEdit.propTypes = {
    handleSubmit: PropTypes.func.isRequired
};

OrgMembersEdit = reduxForm({
    form: 'updateOrgMembersForm'
})(OrgMembersEdit);

export default cssModules(OrgMembersEdit, styles);
```

**Comment by neverfox** [comment]
I'm also experiencing this when my component is further wrapped in redux-forms v6. In my case, it happens inside of the stateless render function passed to the Field `component` prop. The input element in that function is still getting the styleName prop handed to it and React complains.

**Comment by ukdvivek** [comment]
I'm noticing this issue with 3.7.9 even without reduxForm. I simply have this and still get the warning.

`import React from 'react';
import ReactDOM from 'react-dom';
import CSSModules from 'react-css-modules';
import styles from './styles/main';


class App extends React.Component {
    render () {
        return (
            <div styleName='specialCase'>Hello</div>
        );
    }
}

export default CSSModules(App, styles);

ReactDOM.render(<App />, document.getElementById('main'));`

**Comment by gajus** [comment]
Re-opening as there are reports of the issue that need to be investigated.

**Comment by akerr95** [comment]
in the mean time should we just resort to css-module structure.

**Comment by thewillhuang** [comment]
here is a reproducible example

```js
// layout.jsx
import React, { PropTypes } from 'react';
import cssModule from 'react-css-modules';
import style from './layout.css';
import decorator from './ValuePropInjectorPureComponent';

const Layout = props => (
  <div styleName="backgroundColor">
    <h1 styleName="fontColor">
      {`Hi ${props.value}!`}
    </h1>
    {props.children}
  </div>
);

Layout.propTypes = {
  value: PropTypes.string,
  children: PropTypes.arrayOf(PropTypes.element),
};

const valueInjectedPureElement = decorator('Wayne Enterprise')(Layout);
export default cssModule(valueInjectedPureElement, style, { allowMultiple: true });
```
```js
// ValuePropInjectorPureComponent.jsx
// a higher order component
// a function that returns a modified function
import React from 'react';

export const ValuePropInjector = value => Component => props =>
  <Component
    {...{
      ...props,
      value,
    }}
  />;

export default ValuePropInjector;
```
```css
/* layout.css */
.backgroundColor {
  background-color: rgb(236, 236, 236);
}

.fontColor {
  color: grey;
}
```

**Comment by TrippBlunschi** [comment]
Appending styleName with data- should also solve the Typescript error "Property 'styleName' does not exist on type 'HTMLProps<HTMLDivElement>'", since data-* attributes do not appear to be type checked. This used to be resolved with a custom Interface merge. But now that Typescript 2.0 uses scoped packages to install types libraries, the same merge isn't working.

**Comment by hossein761** [comment]
Any news on any possible fix/workaround? We have this issue even in 3.7.10. We appreciate any help ;)

**Comment by jrajav** [comment]
I know it's ugly but the PR I originally submitted at the top of this issue would most likely fix this issue.

**Comment by amyhua** [comment]
Same issue here

**Comment by gajus** [comment]
@amyhua Which version of react-css-modules?

**Comment by amyhua** [comment]
@gajus 3.7.10

**Comment by amyhua** [comment]
I was able to implement a fix using `className={styles.root}`:

```
import React, { Component } from 'react';
import cssModules from 'react-css-modules';
import styles from './UserProfilePage.sass';

class UserProfilePage extends Component {
  render() {
    return (
      <div className={styles.root}>
        <h1>UserProfilePage {this.props.params.username}</h1>
      </div>
    );
  }
}

export default UserProfilePage;
```

**Comment by hossein761** [comment]
The only way that I could make this work is this:
```javascript
import CSSModules from 'react-css-modules';
import styles from 'style.scss'

export default CSSModules(COMPONENT, styles);

```

**Comment by gajus** [comment]
Just upgrade to v4.0.0.

**Comment by hossein761** [comment]
@gajus would my solution break if I upgrade to v4.0.0?

**Comment by gajus** [comment]
> @gajus would my solution above break if I upgrade to v4.0.0?

It should.

**Comment by gajus** [comment]
v4.0.3 is now GA.

**Comment by igagen** [comment]
I am still getting this issue with 4.0.3 and a component that's wrapped in connect (redux).
I'm using decorators and if I reverse the order of the decorators, the error goes away.

Works:

```
import React, { Component } from 'react'
import css from 'react-css-modules'
import { connect } from 'react-redux'

@connect(state => ({ bla: bla(state) }))
@css(styles)
class Bla extends Component {
 // ...
}
```

Error:

```
import React, { Component } from 'react'
import css from 'react-css-modules'
import { connect } from 'react-redux'

@css(styles)
@connect(state => ({ bla: bla(state) }))
class Bla extends Component {
 // ...
}
```

**Comment by tehOPEologist** [comment]
the decorator won't work for me, either.  had to revert to using a wrapper around the component to get it working.  using latest react / react-css-modules.

**Comment by Praveen-Invoscape** [comment]
fixed it ... Problem is in webpack.config file. You need to allow CSS Modules in loader that code is
{
test: /\.css$/,
loader: 'style-loader!css-loader?modules=true'
}

**Comment by linghton** [comment]
@Praveen-Invoscape Can you specify where to put that line into the webpack.config?

**Comment by Praveen-Invoscape** [comment]
You need to specify it in **loaders** that can be in inside the module. Example 
`module: {
      loaders: [
         {
            test: /\.jsx?$/,
            exclude: /node_modules/,
            loader: 'babel',

            query: {
               presets: ['es2015', 'react']
            }
         },
         {
            test: /\.css$/,
            **loader: 'style-loader!css-loader?modules=true'**
         }

      ]
   }`

**Comment by TrippBlunschi** [comment]
I get a similar error with Typescript. "Property 'styleName' does not exist on type 'HTMLProps'". 

Does anyone know of a workaround? 

This worked before Typescript 2.0 (by declaring a custom interface) but doesn't now that we use install type packages type packages. i.e. npm install --save-dev @types/react.

data-styleName would solve this problem, as those attributes are not type checked.

**Comment by dmackerman** [comment]
I'm seeing this as well. I have CSS modules enabled in my webpack config. Not sure where to go from here...using the latest versions of everything.

**Comment by asd0102433** [comment]
@igagen My question is the same as you！

**Comment by josh18** [comment]
Note that in my experience this only seems to be an issue when you exclude the `.less` extension from the import in combination with using the connect wrapper from redux.

This works: `import styles from './styles.less'`

This doesn't: `import styles from './styles'`

No idea why.

**Comment by reywright** [comment]
I'm getting this issue and I'm using version 4.2.0.

**Comment by kortaggio** [comment]
We ran into the same issue but the root cause for us may be different from other reports here. For our application, the underlying issue was that we were rendering our components using enzyme's `shallow()` _without wrapping the component in CSSModules first_. This meant that `styleName` props didn't get converted to `className` props by the CSS modules engine before being passed to the base element.

The solution that worked for us was to convert all un-wrapped components in our tests into wrapped components, as so:

# Before
```jsx
it('renders with my-style', () => {
  const wrapper = shallow(<Foo />);
  expect(wrapper.prop('styleName')).to.equal('my-style');
});
```

# After
```jsx
it('renders with my-style', () => {
  const wrapper = mount(CSSModules(<Foo />, styles));
  expect(wrapper.prop('className')).to.include('Foo__my-style');
});
```

In some instances

**Comment by reywright** [comment]
This is still broken for me. This issue should be reopened

**Comment by Bettelstab** [comment]
@reywright Could you give am example of a working definition? I don't know what you mean by "npm install --save-dev", for me it didn't solve any problems. Any advice would be great.

My code: `import * as React from 'react'
import { buttons } from 'pure-css'
import CSSModules from 'react-css-modules'

const Button = ({ className, children }) => (
  <button className={className} styleName='pure-button'>
    {children}
  </button>
)

export default CSSModules(Button, buttons)
`

**Comment by impressor615** [comment]
@Bettelstab where should I put the code you posted above?

**Comment by Bettelstab** [comment]
@impressor615 I put it in a file "interfaces.d.ts" in my root ts src directory. Add
`import * as React from 'react'` to make it work.

**Comment by wanghairong-i** [comment]
Why didn't I see the right solution?
为什么我没看到正确的解决方案呢？

My solution to this problem is to solve it in TypeScript rather than solve it in this library.
我解决这个问题的方案是在typescript里解决，而非在这个库里解决。

In the root directory，file: /globals.d.ts
```javascript
declare namespace JSX {
  interface IntrinsicElements {
    [elemName: string]: any;
    // 给div元素增加styleName属性，为了兼容 react-css-modules 库
    div: {
      styleName: string;
    }
  }
}
```
