### ISSUE TITLE
react key changed after using react-css-modules

### ISSUE THREAD

**Issue by linwei0201** [gajus/react-css-modules#237]
after using react-css-modules, all react key attribute has a prefix '.$' with it, which is confusing when using https://ant.design together.  

For example , my code is like this
![image](https://cloud.githubusercontent.com/assets/12796371/25694326/b280438a-30e0-11e7-8c72-bf59ebfde444.png)

but the final dom is like this
![image](https://cloud.githubusercontent.com/assets/12796371/25694434/3b7ff112-30e1-11e7-920a-af13ed25e06d.png)

so I have to add the prefix '.$' to the prop 'activeKey', it looks weird. Is there any solutions?? or any settings to avoid the useless '.$' prefix when using react-css-modules

**Comment by greelgorke** [comment]
same here

**Comment by le0nik** [comment]
Fixed it in this PR: https://github.com/gajus/react-css-modules/pull/242. The new version of npm package hasn't been released, yet.

**Comment by gajus** [comment]
It was.

https://www.npmjs.com/package/react-css-modules

The latest version is v4.4.0.

**Comment by renaudtertrais** [comment]
Hi,
I still have the problem in `4.7.1`.
Demo: https://codesandbox.io/s/rj96kjjorq

Any ideas ?

**Comment by zenxds** [comment]
still have the problem in 4.7.1
